site_name: ReSpeaker
pages:
  - Overview: index.md
  - 2 Mic Array for Pi: 2_mic_array.md
  - 4 Mic Array for Pi: 4_mic_array.md
  - Linear 4 Mic Array for Pi: linear_4_mic_array.md
  - 6 Mic Array for Pi: 6_mic_array.md
  - USB 4 Mic Array: usb_4_mic_array.md
  - USB 6+1 Mic Array: usb_6+1_mic_array.md
  - ReSpeaker Core v1.0 (MT7688): mt7688_core.md
  - ReSpeaker Core v2.0 (RK3229): rk3229_core.md
  - Make a smart speaker: make_a_smart_speaker.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
google_analytics: ['UA-117094074-1', 'respeaker.io']
